### ISSUE TITLE
Mobile only: Choosing an item from the hamburger menu does not close the menu

### ISSUE THREAD

**Issue by bajalnyt** [newsguildny/nytimesguild.org#1]
(This was observed on Chrome and Firefox on an Android phone)

Steps to reproduce: 
1. On a mobile device , go to the site and tap on the hamburger menu (2 bars on top right)
2. Choose any one item to select it
3. Expectation: the drop-down menu should close and the site content should unfade.

**Comment by smoores-dev** [comment]
Fixed by 284f92f7b34ce8130333194590d82b53da67e3a8!

**Comment by bajalnyt** [comment]
Thank you @SMores for the quick fix!
